import Foundation
import NitroModules
import UIKit

class HybridMatiksStrokeText: HybridMatiksStrokeTextSpec {
    var view: UIView {
        return strokeTextView
    }
    
    private let strokeTextView: StrokeTextView

    public override init() {
        self.strokeTextView = StrokeTextView(frame: .zero)
        super.init()
    }

    // MARK: - Props
    
    var width: Double? = 0 {
        didSet {
            strokeTextView.width = NSNumber(value: width ?? 0)
        }
    }
    
    var text: String = "" {
        didSet {
            strokeTextView.text = text
        }
    }
    
    var fontSize: Double? = 0 {
        didSet {
            strokeTextView.fontSize = NSNumber(value: fontSize ?? 0)
        }
    }
    
    var color: String? = "" {
        didSet {
            strokeTextView.color = color ?? "#000000"
        }
    }
    
    var strokeColor: String? = "" {
        didSet {
            strokeTextView.strokeColor = strokeColor ?? "#FFFFFF"
        }
    }
    
    var strokeWidth: Double? = 0 {
        didSet {
            strokeTextView.strokeWidth = NSNumber(value: strokeWidth ?? 0)
        }
    }
    
    var fontFamily: String? = "" {
        didSet {
            strokeTextView.fontFamily = fontFamily ?? ""
        }
    }
    
    var align: TextAlign? = .center {
        didSet {
            switch align {
            case .left: strokeTextView.align = "left"
            case .right: strokeTextView.align = "right"
            case .center: strokeTextView.align = "center"
            case .none: strokeTextView.align = "center"
            }
        }
    }
    
    var numberOfLines: Double? = 0 {
        didSet {
            strokeTextView.numberOfLines = NSNumber(value: numberOfLines ?? 0)
        }
    }
    
    var ellipsis: Bool? = false {
        didSet {
            strokeTextView.ellipsis = ellipsis ?? false
        }
    }

    // MARK: - Methods
    
    func measureDimensions() -> Dimensions {
        // StrokeTextView.measureDimensions returns [String: NSNumber]
        // We need to return Dimensions struct which is generated by Nitro
        
        let dims = strokeTextView.measureDimensions()
        let w = dims["width"]?.doubleValue ?? 0.0
        let h = dims["height"]?.doubleValue ?? 0.0
        
        // Assuming Dimensions is a generated struct with init(width: Double, height: Double)
        return Dimensions(width: w, height: h)
    }
}
